name: Continuous Deployment and Testing
on: [push]

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: Install surge
        run: npm install -g surge
      
      - name: Install Python dependencies
        run: |
          pip install selenium pytest
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: "latest"
      
      - name: Deploy to test environment
        run: |
          surge ./ practixsao21hds.surge.sh --token 9e3245c4523779c03a01ac588e5a7f1a
          echo "Test environment deployed. Visit: https://practixsao21hds.surge.sh"
      
      - name: Run Selenium Tests
        run: |
          python your_test_script.py  # Replace with your actual test script name
          
      - name: Deploy to production environment
        run: |
          surge ./ practixsao22hds.surge.sh --token 9e3245c4523779c03a01ac588e5a7f1a
          echo "Production environment deployed. Visit: https://practixsao22hds.surge.sh"
