name: Continuous Deployment
on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.2.0
            
            - run: echo "Setting up NodeJs"
            - name: Setup NodeJs
              uses: actions/setup-node@v1
              with:
               node-version: 16.x

            - run: npm install -g surge
            - run: echo "Deploying website"
            - run: surge ./ practixsao21hds.surge.sh --token 9e3245c4523779c03a01ac588e5a7f1a
            - run: echo "entorno de pruebas desplegado, Please visit => practixsao21hds.surge.sh"
            - run: surge ./ practixsao22hds.surge.sh --token 9e3245c4523779c03a01ac588e5a7f1a
            - run: echo "entorno de produccion desplegado, Please visit => practixsao22hds.surge.sh"